[package]
name = "lime"
version = "0.0000000000008"
edition = "2021"
description = "A 2D game engine written in Rust"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
